package com.justin.truckfinder.app;

/**
 * Created by justinmac on 4/18/14.
 */
public class TODO {



    //TODO: Remove all logging from application. before you release it should not log anything
    //TODO: fix and test all your listeners for map / ccalling / etc
    //TODO: CLEAN UP UNUSED CODE
    //TODO: REMOVE FEATURES SO YOU CAN SUBMIT




    //TODO 1. PROGRESS BAR NOT SHOWING UP, NEEDS FIXING.
    //TODO 2. ROTATION CAUSES VOLLEYS TO BE DONE AGAIN; CHECKED FRAGMENT, NEED TO CHECK ACTIVITY.

    //TODO 3. UPDATES TO UI REGARDING FINALIZED LAYOUT;

    //  TODO 3.1 MYCOMPASSVIEW IS DIFFICULT TO MANIPULATE PROPERLY WITHOUT DISTORTION
    //  TODO 3.2 ALTER URL TO BE AN IMPLICIT INTENT TO A WEBSITE WITHIN OR OURSIDE THE APP
    //  TODO 3.3 ELIMINATING SPECIFIC FOOD TRUCKS THAT ARE NOT ACTUALL FOOD TRUCKS
    //  TODO 3.4 ICON UPDATE FOR LAUNCHER ICON
    //  TODO 3.5 ACTION BAR CONTAINING A SHARE BUTTON TO SHARE EITHER EACH FOOD TRUCK's INFO with link to my app
    //      TODO OR TO SIMPLY SOCIAL SHARE MY APP

    // TODO ERROR REPORT TO SUBMIT TO ME; FEEDBACK REGARDING WHICH TRUCKS WEREN'T THERE, FEATURES THEY WANT TO SEE, ETc.

    // TODO WHAT IF SOMEONE LAUNCHES MY APP AND THERE ARE NO FOOD TRUCKS WITHIN A 750 METER VICINITY???


    //TODO REGARDING LAYOUT AN EVEN WEIGHT ON BOTH SIDES, DESIRE TO POPULATE MORE DATA THAN "UNAVAILABLE"
    //TODO 4.0 POTENTIAL USE OF NETWORK REQUEST TO DETAIL PLACES TO GET PLACE HOURS AND PHONE NUMBER
    //TODO 4.1 HOWEVER, THE JSONARRAY WITHIN THE JSON CONTAINS MULTIPLE ARRAYS WITH OBJECTS
    //TODO 4.2 DO NOT KNOW HOW TO SAVE INFORMATION FROM JSON PARSING TO ARRAYS YET

    //TODO MINOR FIXES
    //TODO dialog box asking the user if they really want to call someone
    //TODO implicit intent to share that they visited a food truck using the foodTruck's twitter handle
    //TODO dialog boxes or Toasts where a launched implicit intent will error out or call a non-existent number


    //TODO FINE TUNING
    //TODO COORDINATE RE-MAPPING WORKS ALMOST ALL THE TIME UNLESS ROTATING THE PHONE IMMEDIATELY TO
    //TODO (cont.) or FROM 90 DEGREES TO/FROM 270; it doesn't volley Again, but doesn't
    //TODO register rotation in the log either.


}
